name: weight_scale
description: Flutter package to connect to BLE weight scales.
version: 0.3.0
homepage: https://github.com/octogradiste/weight_scale

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_blue: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  fake_async: ^1.2.0

  mockito: ^5.0.10

  build_runner: ^2.0.5

flutter:
