name: weight_scale
description: Flutter package to connect to BLE weight scales.
version: 0.5.0
homepage: https://github.com/octogradiste/weight_scale
repository: https://github.com/octogradiste/weight_scale 

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.14.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  fake_async: ^1.2.0

  mockito: ^5.0.10

  build_runner: ^2.0.5
  flutter_lints: ^2.0.1
